import ThemeRegistry from '@/components/theme/ThemeRegistry';
import { UserProvider } from '@auth0/nextjs-auth0/client';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <UserProvider>
        <body>
          <ThemeRegistry options={{ key: 'mui' }}>{children}</ThemeRegistry>
        </body>
      </UserProvider>
    </html>
  );
}
