services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - "./data/redis:/data"

  mongodb:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongodb:/data/db
